version: 2.1
orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    executor:
      name: node/default
      tag: '14.13.1'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Build package
          command: |
            yarn install-peers
            yarn build
      - run:
          name: Create package
          command: |
            cp package.json bin/
            npm publish bin --access public

workflows:
  release:
    jobs:
      - build
  version: 2
